USE [master]
GO
/****** Object:  Database [ExampleDatabase]    Script Date: 7/5/2021 2:11:21 PM ******/
CREATE DATABASE [ExampleDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'exampleDatabase', FILENAME = N'C:\Users\emmateva18\exampleDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'exampleDatabase_log', FILENAME = N'C:\Users\emmateva18\exampleDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExampleDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExampleDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExampleDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExampleDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExampleDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExampleDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExampleDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExampleDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExampleDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExampleDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExampleDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExampleDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExampleDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExampleDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExampleDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExampleDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ExampleDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExampleDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExampleDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExampleDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExampleDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExampleDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExampleDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExampleDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ExampleDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [ExampleDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExampleDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExampleDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExampleDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExampleDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ExampleDatabase]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 7/5/2021 2:11:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](30) NOT NULL,
	[FirstName] [nvarchar](32) NOT NULL,
	[LastName] [nvarchar](32) NOT NULL,
	[Email] [varchar](320) NOT NULL,
	[Address] [nvarchar](64) NULL,
	[City] [nvarchar](32) NULL,
	[Age] [int] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK_Users_Age] CHECK  (([Age]>=(0) AND [Age]<=(130)))
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK_Users_Age]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [CK_Users_Email] CHECK  (([Email] like '%_@__%.__%'))
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [CK_Users_Email]
GO
USE [master]
GO
ALTER DATABASE [ExampleDatabase] SET  READ_WRITE 
GO
